CREATE TABLE IF NOT EXISTS public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  role text NOT NULL DEFAULT 'admin',
  email text,
  recovery_codes text,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;

CREATE POLICY IF NOT EXISTS "Allow anon read access to users"
ON public.users
FOR SELECT
TO anon
USING (true);

CREATE POLICY IF NOT EXISTS "Allow anon insert access to users"
ON public.users
FOR INSERT
TO anon
WITH CHECK (true);

CREATE POLICY IF NOT EXISTS "Allow anon update access to users"
ON public.users
FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

-- Seed admin user (password: admin12345)
INSERT INTO public.users (username, password_hash, role)
VALUES (
  'admin',
  '$2y$12$w7w3IC8YnboJCvH5ZvKp6e5fRkteSFO9Mki3F4QfiJ2LC5bQQbF4i',
  'admin'
)
ON CONFLICT (username) DO NOTHING;
